/*
 * Accton Minipack Platform Definitions
 *
 * Copyright (c) 2019 Cumulus Networks, Inc.  All Rights Reserved.
 * Alok Kumar <alok@cumulusnetworks.com>
 *
 * SPDX-License-Identifier:  GPL-2.0+
 *
 */

#ifndef __ACCTON_MINIPACK_PLATFORM_H
#define __ACCTON_MINIPACK_PLATFORM_H

/* FPGA Hardware Descriptor */
struct fpga_desc {
	u8 tgtaddr_rw;	/* target address & r/w bit */
	u8 wr_len_cmd;	/* write length in bytes or a command */
	u8 rd_len;	/* read length */
	u8 control;	/* control bits */
	u8 status;	/* status bits */
	u8 retry;	/* collision retry and retry count */
	u8 rxbytes;	/* received bytes */
	u8 txbytes;	/* transmitted bytes */
	u32 dptr_low;	/* lower 32 bit of the data pointer */
	u32 dptr_high;	/* upper 32 bit of the data pointer */
} __packed;

struct fpga_priv {
	u8 __iomem *pbar;                       /* PCIe base address register */
	struct pci_dev *pci_dev;
	struct fpga_desc *hw;			/* descriptor virt base addr */
	dma_addr_t io_rng_dma;			/* descriptor HW base addr */
};

#define PIM1_BASE 0x40000
#define PIM2_BASE 0x48000
#define PIM3_BASE 0x50000
#define PIM4_BASE 0x58000
#define PIM5_BASE 0x60000
#define PIM6_BASE 0x68000
#define PIM7_BASE 0x70000
#define PIM8_BASE 0x78000

#define PIM_REVISION    0x0000
#define PIM_SYSTEM_LED  0x000C
#define PIM_UP_TIME     0x0014
#define PIM_LED_CONTROL 0x6084
#define MDIO_SOURCE_SEL 0x0218

#define PORT1_LED_CONTROL  0x0310
#define PORT2_LED_CONTROL  0x0314
#define PORT3_LED_CONTROL  0x0318
#define PORT4_LED_CONTROL  0x031C
#define PORT5_LED_CONTROL  0x0320
#define PORT6_LED_CONTROL  0x0324
#define PORT7_LED_CONTROL  0x0328
#define PORT8_LED_CONTROL  0x032C
#define PORT9_LED_CONTROL  0x0330
#define PORT10_LED_CONTROL 0x0334
#define PORT11_LED_CONTROL 0x0338
#define PORT12_LED_CONTROL 0x033C
#define PORT13_LED_CONTROL 0x0340
#define PORT14_LED_CONTROL 0x0344
#define PORT15_LED_CONTROL 0x0348
#define PORT16_LED_CONTROL 0x034C

//Port Interface Module(PIM) register offsets
#define PIM1_REVISION    (PIM1_BASE | PIM_REVISION)
#define PIM2_REVISION    (PIM2_BASE | PIM_REVISION)
#define PIM3_REVISION    (PIM3_BASE | PIM_REVISION)
#define PIM4_REVISION    (PIM4_BASE | PIM_REVISION)
#define PIM5_REVISION    (PIM5_BASE | PIM_REVISION)
#define PIM6_REVISION    (PIM6_BASE | PIM_REVISION)
#define PIM7_REVISION    (PIM7_BASE | PIM_REVISION)
#define PIM8_REVISION    (PIM8_BASE | PIM_REVISION)
#define PIM1_SYSTEM_LED  (PIM1_BASE | PIM_SYSTEM_LED)
#define PIM2_SYSTEM_LED  (PIM2_BASE | PIM_SYSTEM_LED)
#define PIM3_SYSTEM_LED  (PIM3_BASE | PIM_SYSTEM_LED)
#define PIM4_SYSTEM_LED  (PIM4_BASE | PIM_SYSTEM_LED)
#define PIM5_SYSTEM_LED  (PIM5_BASE | PIM_SYSTEM_LED)
#define PIM6_SYSTEM_LED  (PIM6_BASE | PIM_SYSTEM_LED)
#define PIM7_SYSTEM_LED  (PIM7_BASE | PIM_SYSTEM_LED)
#define PIM8_SYSTEM_LED  (PIM8_BASE | PIM_SYSTEM_LED)
#define PIM1_UP_TIME     (PIM1_BASE | PIM_UP_TIME)
#define PIM2_UP_TIME     (PIM2_BASE | PIM_UP_TIME)
#define PIM3_UP_TIME     (PIM3_BASE | PIM_UP_TIME)
#define PIM4_UP_TIME     (PIM4_BASE | PIM_UP_TIME)
#define PIM5_UP_TIME     (PIM5_BASE | PIM_UP_TIME)
#define PIM6_UP_TIME     (PIM6_BASE | PIM_UP_TIME)
#define PIM7_UP_TIME     (PIM7_BASE | PIM_UP_TIME)
#define PIM8_UP_TIME     (PIM8_BASE | PIM_UP_TIME)

#define PIM1_MDIO_SOURCE (PIM1_BASE | MDIO_SOURCE_SEL)
#define PIM2_MDIO_SOURCE (PIM2_BASE | MDIO_SOURCE_SEL)
#define PIM3_MDIO_SOURCE (PIM3_BASE | MDIO_SOURCE_SEL)
#define PIM4_MDIO_SOURCE (PIM4_BASE | MDIO_SOURCE_SEL)
#define PIM5_MDIO_SOURCE (PIM5_BASE | MDIO_SOURCE_SEL)
#define PIM6_MDIO_SOURCE (PIM6_BASE | MDIO_SOURCE_SEL)
#define PIM7_MDIO_SOURCE (PIM7_BASE | MDIO_SOURCE_SEL)
#define PIM8_MDIO_SOURCE (PIM8_BASE | MDIO_SOURCE_SEL)

#define PIM1_LED_CONTROL (PIM1_BASE | PIM_LED_CONTROL)
#define PIM2_LED_CONTROL (PIM2_BASE | PIM_LED_CONTROL)
#define PIM3_LED_CONTROL (PIM3_BASE | PIM_LED_CONTROL)
#define PIM4_LED_CONTROL (PIM4_BASE | PIM_LED_CONTROL)
#define PIM5_LED_CONTROL (PIM5_BASE | PIM_LED_CONTROL)
#define PIM6_LED_CONTROL (PIM6_BASE | PIM_LED_CONTROL)
#define PIM7_LED_CONTROL (PIM7_BASE | PIM_LED_CONTROL)
#define PIM8_LED_CONTROL (PIM8_BASE | PIM_LED_CONTROL)

#define PIM1_PORT1_LED_CONTROL   (PIM1_BASE | PORT1_LED_CONTROL)
#define PIM1_PORT2_LED_CONTROL   (PIM1_BASE | PORT2_LED_CONTROL)
#define PIM1_PORT3_LED_CONTROL   (PIM1_BASE | PORT3_LED_CONTROL)
#define PIM1_PORT4_LED_CONTROL   (PIM1_BASE | PORT4_LED_CONTROL)
#define PIM1_PORT5_LED_CONTROL   (PIM1_BASE | PORT5_LED_CONTROL)
#define PIM1_PORT6_LED_CONTROL   (PIM1_BASE | PORT6_LED_CONTROL)
#define PIM1_PORT7_LED_CONTROL   (PIM1_BASE | PORT7_LED_CONTROL)
#define PIM1_PORT8_LED_CONTROL   (PIM1_BASE | PORT8_LED_CONTROL)
#define PIM1_PORT9_LED_CONTROL   (PIM1_BASE | PORT9_LED_CONTROL)
#define PIM1_PORT10_LED_CONTROL  (PIM1_BASE | PORT10_LED_CONTROL)
#define PIM1_PORT11_LED_CONTROL  (PIM1_BASE | PORT11_LED_CONTROL)
#define PIM1_PORT12_LED_CONTROL  (PIM1_BASE | PORT12_LED_CONTROL)
#define PIM1_PORT13_LED_CONTROL  (PIM1_BASE | PORT13_LED_CONTROL)
#define PIM1_PORT14_LED_CONTROL  (PIM1_BASE | PORT14_LED_CONTROL)
#define PIM1_PORT15_LED_CONTROL  (PIM1_BASE | PORT15_LED_CONTROL)
#define PIM1_PORT16_LED_CONTROL  (PIM1_BASE | PORT16_LED_CONTROL)

#define PIM2_PORT1_LED_CONTROL   (PIM2_BASE | PORT1_LED_CONTROL)
#define PIM2_PORT2_LED_CONTROL   (PIM2_BASE | PORT2_LED_CONTROL)
#define PIM2_PORT3_LED_CONTROL   (PIM2_BASE | PORT3_LED_CONTROL)
#define PIM2_PORT4_LED_CONTROL   (PIM2_BASE | PORT4_LED_CONTROL)
#define PIM2_PORT5_LED_CONTROL   (PIM2_BASE | PORT5_LED_CONTROL)
#define PIM2_PORT6_LED_CONTROL   (PIM2_BASE | PORT6_LED_CONTROL)
#define PIM2_PORT7_LED_CONTROL   (PIM2_BASE | PORT7_LED_CONTROL)
#define PIM2_PORT8_LED_CONTROL   (PIM2_BASE | PORT8_LED_CONTROL)
#define PIM2_PORT9_LED_CONTROL   (PIM2_BASE | PORT9_LED_CONTROL)
#define PIM2_PORT10_LED_CONTROL  (PIM2_BASE | PORT10_LED_CONTROL)
#define PIM2_PORT11_LED_CONTROL  (PIM2_BASE | PORT11_LED_CONTROL)
#define PIM2_PORT12_LED_CONTROL  (PIM2_BASE | PORT12_LED_CONTROL)
#define PIM2_PORT13_LED_CONTROL  (PIM2_BASE | PORT13_LED_CONTROL)
#define PIM2_PORT14_LED_CONTROL  (PIM2_BASE | PORT14_LED_CONTROL)
#define PIM2_PORT15_LED_CONTROL  (PIM2_BASE | PORT15_LED_CONTROL)
#define PIM2_PORT16_LED_CONTROL  (PIM2_BASE | PORT16_LED_CONTROL)

#define PIM3_PORT1_LED_CONTROL   (PIM3_BASE | PORT1_LED_CONTROL)
#define PIM3_PORT2_LED_CONTROL   (PIM3_BASE | PORT2_LED_CONTROL)
#define PIM3_PORT3_LED_CONTROL   (PIM3_BASE | PORT3_LED_CONTROL)
#define PIM3_PORT4_LED_CONTROL   (PIM3_BASE | PORT4_LED_CONTROL)
#define PIM3_PORT5_LED_CONTROL   (PIM3_BASE | PORT5_LED_CONTROL)
#define PIM3_PORT6_LED_CONTROL   (PIM3_BASE | PORT6_LED_CONTROL)
#define PIM3_PORT7_LED_CONTROL   (PIM3_BASE | PORT7_LED_CONTROL)
#define PIM3_PORT8_LED_CONTROL   (PIM3_BASE | PORT8_LED_CONTROL)
#define PIM3_PORT9_LED_CONTROL   (PIM3_BASE | PORT9_LED_CONTROL)
#define PIM3_PORT10_LED_CONTROL  (PIM3_BASE | PORT10_LED_CONTROL)
#define PIM3_PORT11_LED_CONTROL  (PIM3_BASE | PORT11_LED_CONTROL)
#define PIM3_PORT12_LED_CONTROL  (PIM3_BASE | PORT12_LED_CONTROL)
#define PIM3_PORT13_LED_CONTROL  (PIM3_BASE | PORT13_LED_CONTROL)
#define PIM3_PORT14_LED_CONTROL  (PIM3_BASE | PORT14_LED_CONTROL)
#define PIM3_PORT15_LED_CONTROL  (PIM3_BASE | PORT15_LED_CONTROL)
#define PIM3_PORT16_LED_CONTROL  (PIM3_BASE | PORT16_LED_CONTROL)

#define PIM4_PORT1_LED_CONTROL   (PIM4_BASE | PORT1_LED_CONTROL)
#define PIM4_PORT2_LED_CONTROL   (PIM4_BASE | PORT2_LED_CONTROL)
#define PIM4_PORT3_LED_CONTROL   (PIM4_BASE | PORT3_LED_CONTROL)
#define PIM4_PORT4_LED_CONTROL   (PIM4_BASE | PORT4_LED_CONTROL)
#define PIM4_PORT5_LED_CONTROL   (PIM4_BASE | PORT5_LED_CONTROL)
#define PIM4_PORT6_LED_CONTROL   (PIM4_BASE | PORT6_LED_CONTROL)
#define PIM4_PORT7_LED_CONTROL   (PIM4_BASE | PORT7_LED_CONTROL)
#define PIM4_PORT8_LED_CONTROL   (PIM4_BASE | PORT8_LED_CONTROL)
#define PIM4_PORT9_LED_CONTROL   (PIM4_BASE | PORT9_LED_CONTROL)
#define PIM4_PORT10_LED_CONTROL  (PIM4_BASE | PORT10_LED_CONTROL)
#define PIM4_PORT11_LED_CONTROL  (PIM4_BASE | PORT11_LED_CONTROL)
#define PIM4_PORT12_LED_CONTROL  (PIM4_BASE | PORT12_LED_CONTROL)
#define PIM4_PORT13_LED_CONTROL  (PIM4_BASE | PORT13_LED_CONTROL)
#define PIM4_PORT14_LED_CONTROL  (PIM4_BASE | PORT14_LED_CONTROL)
#define PIM4_PORT15_LED_CONTROL  (PIM4_BASE | PORT15_LED_CONTROL)
#define PIM4_PORT16_LED_CONTROL  (PIM4_BASE | PORT16_LED_CONTROL)

#define PIM5_PORT1_LED_CONTROL   (PIM5_BASE | PORT1_LED_CONTROL)
#define PIM5_PORT2_LED_CONTROL   (PIM5_BASE | PORT2_LED_CONTROL)
#define PIM5_PORT3_LED_CONTROL   (PIM5_BASE | PORT3_LED_CONTROL)
#define PIM5_PORT4_LED_CONTROL   (PIM5_BASE | PORT4_LED_CONTROL)
#define PIM5_PORT5_LED_CONTROL   (PIM5_BASE | PORT5_LED_CONTROL)
#define PIM5_PORT6_LED_CONTROL   (PIM5_BASE | PORT6_LED_CONTROL)
#define PIM5_PORT7_LED_CONTROL   (PIM5_BASE | PORT7_LED_CONTROL)
#define PIM5_PORT8_LED_CONTROL   (PIM5_BASE | PORT8_LED_CONTROL)
#define PIM5_PORT9_LED_CONTROL   (PIM5_BASE | PORT9_LED_CONTROL)
#define PIM5_PORT10_LED_CONTROL  (PIM5_BASE | PORT10_LED_CONTROL)
#define PIM5_PORT11_LED_CONTROL  (PIM5_BASE | PORT11_LED_CONTROL)
#define PIM5_PORT12_LED_CONTROL  (PIM5_BASE | PORT12_LED_CONTROL)
#define PIM5_PORT13_LED_CONTROL  (PIM5_BASE | PORT13_LED_CONTROL)
#define PIM5_PORT14_LED_CONTROL  (PIM5_BASE | PORT14_LED_CONTROL)
#define PIM5_PORT15_LED_CONTROL  (PIM5_BASE | PORT15_LED_CONTROL)
#define PIM5_PORT16_LED_CONTROL  (PIM5_BASE | PORT16_LED_CONTROL)

#define PIM6_PORT1_LED_CONTROL   (PIM6_BASE | PORT1_LED_CONTROL)
#define PIM6_PORT2_LED_CONTROL   (PIM6_BASE | PORT2_LED_CONTROL)
#define PIM6_PORT3_LED_CONTROL   (PIM6_BASE | PORT3_LED_CONTROL)
#define PIM6_PORT4_LED_CONTROL   (PIM6_BASE | PORT4_LED_CONTROL)
#define PIM6_PORT5_LED_CONTROL   (PIM6_BASE | PORT5_LED_CONTROL)
#define PIM6_PORT6_LED_CONTROL   (PIM6_BASE | PORT6_LED_CONTROL)
#define PIM6_PORT7_LED_CONTROL   (PIM6_BASE | PORT7_LED_CONTROL)
#define PIM6_PORT8_LED_CONTROL   (PIM6_BASE | PORT8_LED_CONTROL)
#define PIM6_PORT9_LED_CONTROL   (PIM6_BASE | PORT9_LED_CONTROL)
#define PIM6_PORT10_LED_CONTROL  (PIM6_BASE | PORT10_LED_CONTROL)
#define PIM6_PORT11_LED_CONTROL  (PIM6_BASE | PORT11_LED_CONTROL)
#define PIM6_PORT12_LED_CONTROL  (PIM6_BASE | PORT12_LED_CONTROL)
#define PIM6_PORT13_LED_CONTROL  (PIM6_BASE | PORT13_LED_CONTROL)
#define PIM6_PORT14_LED_CONTROL  (PIM6_BASE | PORT14_LED_CONTROL)
#define PIM6_PORT15_LED_CONTROL  (PIM6_BASE | PORT15_LED_CONTROL)
#define PIM6_PORT16_LED_CONTROL  (PIM6_BASE | PORT16_LED_CONTROL)

#define PIM7_PORT1_LED_CONTROL   (PIM7_BASE | PORT1_LED_CONTROL)
#define PIM7_PORT2_LED_CONTROL   (PIM7_BASE | PORT2_LED_CONTROL)
#define PIM7_PORT3_LED_CONTROL   (PIM7_BASE | PORT3_LED_CONTROL)
#define PIM7_PORT4_LED_CONTROL   (PIM7_BASE | PORT4_LED_CONTROL)
#define PIM7_PORT5_LED_CONTROL   (PIM7_BASE | PORT5_LED_CONTROL)
#define PIM7_PORT6_LED_CONTROL   (PIM7_BASE | PORT6_LED_CONTROL)
#define PIM7_PORT7_LED_CONTROL   (PIM7_BASE | PORT7_LED_CONTROL)
#define PIM7_PORT8_LED_CONTROL   (PIM7_BASE | PORT8_LED_CONTROL)
#define PIM7_PORT9_LED_CONTROL   (PIM7_BASE | PORT9_LED_CONTROL)
#define PIM7_PORT10_LED_CONTROL  (PIM7_BASE | PORT10_LED_CONTROL)
#define PIM7_PORT11_LED_CONTROL  (PIM7_BASE | PORT11_LED_CONTROL)
#define PIM7_PORT12_LED_CONTROL  (PIM7_BASE | PORT12_LED_CONTROL)
#define PIM7_PORT13_LED_CONTROL  (PIM7_BASE | PORT13_LED_CONTROL)
#define PIM7_PORT14_LED_CONTROL  (PIM7_BASE | PORT14_LED_CONTROL)
#define PIM7_PORT15_LED_CONTROL  (PIM7_BASE | PORT15_LED_CONTROL)
#define PIM7_PORT16_LED_CONTROL  (PIM7_BASE | PORT16_LED_CONTROL)

#define PIM8_PORT1_LED_CONTROL   (PIM8_BASE | PORT1_LED_CONTROL)
#define PIM8_PORT2_LED_CONTROL   (PIM8_BASE | PORT2_LED_CONTROL)
#define PIM8_PORT3_LED_CONTROL   (PIM8_BASE | PORT3_LED_CONTROL)
#define PIM8_PORT4_LED_CONTROL   (PIM8_BASE | PORT4_LED_CONTROL)
#define PIM8_PORT5_LED_CONTROL   (PIM8_BASE | PORT5_LED_CONTROL)
#define PIM8_PORT6_LED_CONTROL   (PIM8_BASE | PORT6_LED_CONTROL)
#define PIM8_PORT7_LED_CONTROL   (PIM8_BASE | PORT7_LED_CONTROL)
#define PIM8_PORT8_LED_CONTROL   (PIM8_BASE | PORT8_LED_CONTROL)
#define PIM8_PORT9_LED_CONTROL   (PIM8_BASE | PORT9_LED_CONTROL)
#define PIM8_PORT10_LED_CONTROL  (PIM8_BASE | PORT10_LED_CONTROL)
#define PIM8_PORT11_LED_CONTROL  (PIM8_BASE | PORT11_LED_CONTROL)
#define PIM8_PORT12_LED_CONTROL  (PIM8_BASE | PORT12_LED_CONTROL)
#define PIM8_PORT13_LED_CONTROL  (PIM8_BASE | PORT13_LED_CONTROL)
#define PIM8_PORT14_LED_CONTROL  (PIM8_BASE | PORT14_LED_CONTROL)
#define PIM8_PORT15_LED_CONTROL  (PIM8_BASE | PORT15_LED_CONTROL)
#define PIM8_PORT16_LED_CONTROL  (PIM8_BASE | PORT16_LED_CONTROL)

//System CPLD registers
#define BOARD_INFO               0x00
#define CPLD_VER                 0x01
#define CPLD_SUB_VER             0x02
#define POWER_MOD_L_STATUS       0x03
#define POWER_MOD_R_STATUS       0x04
#define SYS_RESET_2              0x06
#define PIM_FPGA_PRESENT         0x32
#define SCM_FCM_PRESENT          0x35

#endif
